---
- hosts: dev
  tasks:
  - name: Ensure git install
    ansible.builtin.git:
      name: git
      state: present
      ubdate_cache: true
      single_branch: yes
    become: true
  - name: Example clone of a single branch
    ansible.builtin.git:
      repo: git@github.com:matanelg/circleci-test.git
      dest: /home/ubuntu/repos
      key_file: /home/ubuntu/.ssh/github
      version: a
# src - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html